import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "styled-components";

const indexContainer = styles.div`
width: 100%;
height:100%;
background: linear-gradient(rgb(0 0 0 / 73%),rgb(0 0 0 / 54%)) ,url(/bg-anime6.jpg)no-repeat fixed;
    background-position: center top;
background-size: cover;
overflow:hidden;
}
}
`;

export default function Home() {
  const [s, setS] = useState(1000);

  useEffect(() => {
    setS(2000);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`w-[${s}px] bg-black`}>
        <h2>123</h2>
      </div>
    </div>
  );
}
